### ISSUE TITLE
`load-wasm` Error:`Actor` not initialized

### ISSUE THREAD

**Issue by sadernalwis** [B3Pay/B3Wallet#43]
Meanwhile, a backend error during
`npx ts-node scripts/load-wasm.system.ts`:

`Actor` not initialized

```typescript
updateAgent(mainnet)
  .then(() => callSystemMethod("version"))
```
```bash
RUNNING:        Uploading B3 System WASM
Network: local
Reload: false
Identity: g6fl7-zsssh-dt4jw-ktisy-4sboy-c3zez-pnbwo-ia64c-6r74t-4uwq7-vae
Initializing actor undefined on local network
Error in initializeActor: AgentError: Canister ID is required, but received undefined instead. If you are using automatically generated declarations, this may be because your application is not setting the canister ID in process.env correctly.
    at Function.createActor (~/B3/node_modules/@dfinity/agent/src/actor.ts:324:13)
    at ActorManager.initializeActor (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:56:44)
    at ~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:79:52
    at Array.forEach (<anonymous>)
    at AgentManager.notifySubscribers (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:79:30)
    at AgentManager.<anonymous> (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:90:18)
    at Generator.next (<anonymous>)
    at fulfilled (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:19:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Actor not initialized
    at ActorManager.<anonymous> (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:75:23)
    at Generator.next (<anonymous>)
    at ~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:18:12)
    at ActorManager.callMethod (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:73:54)
    at ~/B3/scripts/load-wasm.system.ts:152:31
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by b3hr4d** [comment]
this is the error `Canister ID is required, but received undefined instead.` you need to `source .env` because it fetch canisterId from `.env` file.

**Comment by sadernalwis** [comment]
still persists. Cannot figure out where the `Canister ID` is checked.!

**Comment by b3hr4d** [comment]
check this

https://github.com/B3Pay/B3Wallet/blob/fe023403ab92f6bac6169f4bc05c567bbca4697e/scripts/b3system.ts#L2C1-L2C80

this will read from the `declarations` then from `.env` file.

**Comment by sadernalwis** [comment]
sorry, my typescript knowledge is subpar. 
`canisterId` exported by the `b3system,` is a type.
and its `undefined`.

**Comment by b3hr4d** [comment]
> `canisterId` exported by the `b3system,` is a type.

Yes on the `index.d.ts`(just for type annotation) is a type, but on the `index.js`(actual logic): 
```js
export const canisterId = process.env.CANISTER_ID_B3SYSTEM || process.env.B3SYSTEM_CANISTER_ID;
```

**Comment by sadernalwis** [comment]
can u reproduce this error.?

**Comment by b3hr4d** [comment]
No, I didn't face this issue, I guess it's because of the `AUTOBUILD` script doesn't have read access that `.env` file!

**Comment by sadernalwis** [comment]
`src ./env` seems to work.
`process.env.CANISTER_ID_B3SYSTEM || process.env.B3SYSTEM_CANISTER_ID`
returns a successful canister ID.

I will investigate further.

**Comment by b3hr4d** [comment]
So you shouldn't get `AgentError: Canister ID is required` error anymore right?!

**Comment by sadernalwis** [comment]
somehow the `index.js` is not loaded, maybe?!
coz I get the error even without the `autobuild` script.

**Comment by b3hr4d** [comment]
Verify you have `.env` file on the root directory and have `B3SYSTEM_CANISTER_ID` variable, then run this `source .env` then run `yarn load-wasm:system`.

**Comment by sadernalwis** [comment]
1. `.env` present
2. `source .env`
3. `yarn load-wasm:system`

no joy!

```bash
$ npm ls typescript
b3wallet@0.5.1 ~/B3
├─┬ eslint-config-next@14.0.4
│ ├─┬ @typescript-eslint/parser@6.18.1
│ │ └─┬ @typescript-eslint/typescript-estree@6.18.1
│ │   └─┬ ts-api-utils@1.0.3
│ │     └── typescript@5.3.3 deduped
│ └── typescript@5.3.3 deduped
├─┬ ts-node@10.9.2
│ └── typescript@5.3.3 deduped
└── typescript@5.3.3
```

**Comment by b3hr4d** [comment]
did you get exact this

> ```shell
> RUNNING:        Uploading B3 System WASM
> Network: local
> Reload: false
> Identity: g6fl7-zsssh-dt4jw-ktisy-4sboy-c3zez-pnbwo-ia64c-6r74t-4uwq7-vae
> Initializing actor undefined on local network
> Error in initializeActor: AgentError: Canister ID is required, but received undefined instead. If you are using automatically generated declarations, this may be because your application is not setting the canister ID in process.env correctly.
>     at Function.createActor (~/B3/node_modules/@dfinity/agent/src/actor.ts:324:13)
>     at ActorManager.initializeActor (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:56:44)
>     at ~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:79:52
>     at Array.forEach (<anonymous>)
>     at AgentManager.notifySubscribers (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:79:30)
>     at AgentManager.<anonymous> (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:90:18)
>     at Generator.next (<anonymous>)
>     at fulfilled (~/B3/node_modules/@ic-reactor/store/dist/agent/index.js:19:58)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> Error: Actor not initialized
>     at ActorManager.<anonymous> (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:75:23)
>     at Generator.next (<anonymous>)
>     at ~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:22:71
>     at new Promise (<anonymous>)
>     at __awaiter (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:18:12)
>     at ActorManager.callMethod (~/B3/node_modules/@ic-reactor/store/dist/actor/index.js:73:54)
>     at ~/B3/scripts/load-wasm.system.ts:152:31
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
> ```

error?

**Comment by b3hr4d** [comment]
please add `require("dotenv").config()` on top of the `scripts/b3system.ts` file and try it again.

**Comment by sadernalwis** [comment]
phew.. works!! 😃
thank you..🙏🙏🙏

**Comment by sadernalwis** [comment]
nice.. finally have a good build..!!

**Comment by b3hr4d** [comment]
Thanks for the effort and good job!

**Comment by sadernalwis** [comment]
Go TEAM!!!
